# fly --target obstacle_concourse login --concourse-url http://127.0.0.1:8080
# fly -t tutorial set-pipeline -c pipeline.yml -p obstacle_concourse
# fly -t obstacle_concourse unpause-pipeline -p obstacle_concourse
# ...then login to main with the UI and start the job


---
resources:
- name: obstacle_concourse
  type: git
  source:
    uri: https://github.com/fordprior/obstacle_concourse
    branch: master

jobs:
- name: test
  plan:
  - get: obstacle_concourse
  - task: run-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ruby
      inputs:
      - name: obstacle_concourse
      run:
        path: /bin/bash
        args:
        - -c
        - |
          cd obstacle_concourse
          bundle install
          bundle exec rspec