# fly -t tutorial set-pipeline -c pipeline.yml -p helloworld

---
resources:
- name: flight-school
  type: git
  source:
    uri: https://github.com/fordprior/obstacle_concourse
    branch: master

jobs:
- name: test
  plan:
  - get: obstacle_concourse
  - task: run-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ruby
      inputs:
      - name: obstacle_concourse
      run:
        path: /bin/bash
        args:
        - -c
        - |
          cd obstacle_concourse
          bundle install
          bundle exec rspec